all:
  vars:
    volume_path: "/home/{{ ansible_env.SUDO_USER or ansible_user_id }}/docker_volume"
    pg_postgres_password: ""
    pg_grafana_password: ""
    gf_admin_password: ""
  hosts:
    vm-dev:
      ansible_host: "192.168.64.3"
      ansible_ssh_pass: "{{ lookup('ansible.builtin.env', 'SSHPASSWORD') }}"
