global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'haproxy'
    static_configs:
      - targets:
          - "haproxy:8405"
  - job_name: 'etcd'
    scheme: https
    tls_config:
      ca_file: /etc/ssl/ca.crt
    static_configs:
      - targets:
          - "etcd1:2379"
          - "etcd2:2379"
          - "etcd3:2379"
  - job_name: 'postgres'
    static_configs:
      - targets:
          - "postgres1-exporter:9187"
          - "postgres2-exporter:9187"
  - job_name: 'pgbouncer'
    static_configs:
      - targets:
          - "pgbouncer1-exporter:9127"
          - "pgbouncer2-exporter:9127"
  - job_name: 'minio'
    scheme: https
    tls_config:
      ca_file: /etc/ssl/ca.crt
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
          - "minio1:9000"
          - "minio2:9000"
