- name: Run Postgres
  hosts: all
  become: true
  tasks:
    - name: Create postgres network
      docker_network:
        name: postgres-net
    - name: Postgres volume dir
      file:
        path: "{{ volume_path }}/postgres"
        state: directory
        owner: "999"
        group: "999"
    - name: Postgres Container
      docker_container:
        name: postgres
        image: postgres:16.3
        restart_policy: always
        networks:
          - name: postgres-net
        volumes:
          - "{{ volume_path }}/postgres:/var/lib/postgresql/data"
        published_ports:
          - 127.0.0.1:5432:5432
        env:
          TZ: Asia/Jakarta
          POSTGRES_PASSWORD: "{{ pg_postgres_password }}"
